### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by skyebird189** [piegfx/mixr#1]
A list of things that need fixing/adding in order of priority.

- [x] Fix wave loader (IMPORTANT!!!)
- [x] Ability to seek, in both seconds and samples
- [x] Fix popping sound when streaming audio when interpolation is enabled
- [x] Set audio system properties, such as master volume
- [x] Fix stream popping when speed < 1
- [ ] Get channel properties, including current position
- [ ] SIMD resampling
- [ ] Vorbis, MP3, FLAC, etc loaders.
- [ ] Reverse sample playing
- [ ] Effects such as low and high-pass filters, echo
